name       : dfu-util
version    : '0.9'
release    : 1
source     :
    - http://dfu-util.sourceforge.net/releases/dfu-util-0.9.tar.gz : 36428c6a6cb3088cad5a3592933385253da5f29f2effa61518ee5991ea38f833
license    : GPL-2.0-only
component  : programming.tools
summary    : Device Firmware Upgrade Utilities
description: |
    Device Firmware Upgrade Utilities
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
